language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler
  - bundle --version
  - mkdir -p tmp/bundle

bundler_args: "--binstubs"

script: ./test/test_with_railsapp

rvm: 
  - 1.8.7

gemfile:
  - test/rails_2.3.gemfile

env: 
  - INSTALL_AS=plugin
  - INSTALL_AS=gem
