language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler
  - bundle --version

bundler_args: "--binstubs"

rvm: 
  - 2.0.0

matrix:
  allow_failures:
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: rbx
    - rvm: jruby-head

  include:
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: 2.0.0
    - rvm: rbx
    - rvm: jruby-head

