# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{SciMed-bj}
  s.version = "1.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ara T. Howard", "Joshua Warchol", "Jens Kraemer"]
  s.date = %q{2011-08-23}
  s.default_executable = %q{bj}
  s.description = %q{Forked ahoward/bj because the way the bin/bj before_run method interacts with Main's logger= instance menthod breaks in Ruby 1.8.7. Forked again to add missing 'require logger'}
  s.email = ["josh.warchol@vibes.com", "jk@jkraemer.net"]
  s.executables = ["bj"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README",
    "TODO"
  ]
  s.files = [
    "HISTORY",
    "LICENSE",
    "README",
    "Rakefile",
    "SciMed-bj.gemspec",
    "TODO",
    "VERSION",
    "bin/bj",
    "init.rb",
    "install.rb",
    "lib/bj.rb",
    "lib/bj/api.rb",
    "lib/bj/bj.rb",
    "lib/bj/errors.rb",
    "lib/bj/joblist.rb",
    "lib/bj/logger.rb",
    "lib/bj/runner.rb",
    "lib/bj/stdext.rb",
    "lib/bj/table.rb",
    "lib/bj/util.rb",
    "plugin/HISTORY",
    "plugin/README",
    "plugin/Rakefile",
    "plugin/init.rb",
    "plugin/install.rb",
    "plugin/script/bj",
    "plugin/tasks/bj_tasks.rake",
    "plugin/test/bj_test.rb",
    "plugin/uninstall.rb",
    "todo.yml"
  ]
  s.homepage = %q{http://github.com/jkraemer/bj}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.4.2}
  s.summary = %q{Minor fork of ahoward/bj}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<main>, [">= 2.6.0"])
      s.add_runtime_dependency(%q<systemu>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<orderedhash>, [">= 0.0.3"])
    else
      s.add_dependency(%q<main>, [">= 2.6.0"])
      s.add_dependency(%q<systemu>, [">= 1.2.0"])
      s.add_dependency(%q<orderedhash>, [">= 0.0.3"])
    end
  else
    s.add_dependency(%q<main>, [">= 2.6.0"])
    s.add_dependency(%q<systemu>, [">= 1.2.0"])
    s.add_dependency(%q<orderedhash>, [">= 0.0.3"])
  end
end

