# A sample Gemfile
source "https://rubygems.org"

ruby '1.8.7'

gem "rails", '~> 2.1.0'

#gem 'activerecord-postgresql-adapter'
gem 'sqlite3'
gem 'rdoc'

group 'test' do
  gem 'bacon'
  gem 'main', '>= 2.6.0'
  gem 'systemu', '>= 1.2.0'
  gem 'orderedhash', '>= 0.0.3'
  gem 'rake', '>= 0.9.6'
end
